
class helper:

    def returnObject(
                    tcg,
                    api_id,
                    name,
                    image,
                    set,
                    set_code,
                    card_id,
                    rarity,
                    price,
                    price_foil,
                    price_other,
                    type,
                    subtype,
                    game_text,
                    flavor_text,
                    cost,
                    cost_text,
                    attack,
                    defence,
                    kind,
                    lotr_resistance,
                    keywords,
                    lotr_culture,
                    lotr_home_site,
                ):
        return {    "tcg": tcg,
                    "api_id": api_id,   
                    "name": name,   
                    "image": image,   
                    "set": set,   
                    "set_code": set_code,   
                    "card_id": card_id,   
                    "rarity": rarity,   
                    "price": price,
                    "price_foil": price_foil,
                    "price_other": price_other,
                    "type": type,  
                    "subtype": subtype,  
                    "game_text": game_text,  
                    "flavor_text": flavor_text,  
                    "cost": cost,      
                    "cost_text": cost_text,
                    "attack": attack,       
                    "defence": defence,       
                    "kind": kind,
                    "lotr_resistance": lotr_resistance,
                    "keywords" : keywords,
                    "lotr_culture": lotr_culture,
                    "lotr_home_site": lotr_home_site,
                }